#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  DailyDo — install terminal command
#  Adds "dailydo" to your shell so you can launch the app
#  from anywhere with a single word.
#
#  Usage:
#    bash scripts/install-cli.sh
# ─────────────────────────────────────────────────────────────

set -e

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LAUNCH_SCRIPT="$APP_DIR/scripts/launch.sh"

# ── Create the launch script ──────────────────────────────────
cat > "$LAUNCH_SCRIPT" << LAUNCH
#!/usr/bin/env bash
# Auto-generated by install-cli.sh — do not edit directly
cd "$APP_DIR"

# Try Tauri desktop app first; fall back to browser dev mode
if command -v cargo >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
  echo "Launching DailyDo (desktop)…"
  npm run tauri:dev
elif command -v npm >/dev/null 2>&1; then
  echo "Launching DailyDo (browser)…"
  npm run dev
else
  echo "Error: npm not found. Install Node.js first: https://nodejs.org"
  exit 1
fi
LAUNCH

chmod +x "$LAUNCH_SCRIPT"
echo "✓  Created launch script: $LAUNCH_SCRIPT"

# ── Detect shell config file ──────────────────────────────────
detect_shell_rc() {
  if [[ "$SHELL" == */zsh ]]; then
    echo "$HOME/.zshrc"
  elif [[ "$SHELL" == */bash ]]; then
    echo "$HOME/.bash_profile"
  else
    echo "$HOME/.profile"
  fi
}

SHELL_RC="$(detect_shell_rc)"
ALIAS_LINE="alias dailydo='$LAUNCH_SCRIPT'"

# ── Add alias if not already present ─────────────────────────
if grep -qF "alias dailydo=" "$SHELL_RC" 2>/dev/null; then
  echo "✓  'dailydo' alias already exists in $SHELL_RC"
else
  {
    echo ""
    echo "# DailyDo — todo widget"
    echo "$ALIAS_LINE"
  } >> "$SHELL_RC"
  echo "✓  Added 'dailydo' alias to $SHELL_RC"
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Installation complete!"
echo ""
echo "  Activate now (or open a new terminal):"
echo "    source $SHELL_RC"
echo ""
echo "  Then launch DailyDo anytime with:"
echo "    dailydo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
